// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlgen

import (
	"database/sql"
	"time"
)

type Subscription struct {
	ID          sql.NullInt64
	ServiceName string
	Price       int32
	UserUuid    []byte
	StartDate   time.Time
	EndDate     sql.NullTime
	CanceledAt  sql.NullTime
}
