// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlgen

import (
	"context"
	"database/sql"
	"time"
)

const calculateSubscriptionsRevenue = `-- name: CalculateSubscriptionsRevenue :one
SELECT
    COALESCE(
        SUM(
            price * (EXTRACT(MONTH FROM overlap_end) - EXTRACT(MONTH FROM overlap_start) +
            (EXTRACT(YEAR FROM overlap_end) - EXTRACT(YEAR FROM overlap_start)) * 12 + 1)
        ),
    0) :: INT
FROM (
    SELECT
        price,
        LEAST($1, cancelation_date, end_date) AS overlap_end,
        GREATEST($2, start_date) AS overlap_start
    FROM subscriptions
    WHERE
        tsrange(
            $2::DATE,
            $1::DATE + INTERVAL '1 month'
        ) && tsrange(
            start_date,
            end_date + INTERVAL '1 month'
        ) AND
        user_uuid = COALESCE($3, user_uuid) AND
        service_name = COALESCE($4, service_name)
)
`

type CalculateSubscriptionsRevenueParams struct {
	PeriodEnd   sql.NullTime
	PeriodStart sql.NullTime
	UserUuid    []byte
	ServiceName sql.NullString
}

func (q *Queries) CalculateSubscriptionsRevenue(ctx context.Context, arg CalculateSubscriptionsRevenueParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, calculateSubscriptionsRevenue,
		arg.PeriodEnd,
		arg.PeriodStart,
		arg.UserUuid,
		arg.ServiceName,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const cancelSubscriptionByID = `-- name: CancelSubscriptionByID :execrows
UPDATE subscriptions SET
    cancelation_date = COALESCE(cancelation_date, $1)
WHERE
    id = $2 AND
    COALESCE(end_date >= $1, TRUE)
`

type CancelSubscriptionByIDParams struct {
	CancelationDate sql.NullTime
	ID              sql.NullInt64
}

func (q *Queries) CancelSubscriptionByID(ctx context.Context, arg CancelSubscriptionByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelSubscriptionByID, arg.CancelationDate, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    service_name,
    price,
    user_uuid,
    start_date,
    end_date    
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5    
) RETURNING id, service_name, price, user_uuid, start_date, end_date, cancelation_date
`

type CreateSubscriptionParams struct {
	ServiceName string
	Price       int32
	UserUuid    []byte
	StartDate   time.Time
	EndDate     sql.NullTime
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, createSubscription,
		arg.ServiceName,
		arg.Price,
		arg.UserUuid,
		arg.StartDate,
		arg.EndDate,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserUuid,
		&i.StartDate,
		&i.EndDate,
		&i.CancelationDate,
	)
	return i, err
}

const getAllSubscriptions = `-- name: GetAllSubscriptions :many
SELECT id, service_name, price, user_uuid, start_date, end_date, cancelation_date FROM subscriptions
WHERE
    user_uuid = COALESCE($1, user_uuid) AND
    service_name = COALESCE($2, service_name)
`

type GetAllSubscriptionsParams struct {
	UserUuid    []byte
	ServiceName sql.NullString
}

func (q *Queries) GetAllSubscriptions(ctx context.Context, arg GetAllSubscriptionsParams) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, getAllSubscriptions, arg.UserUuid, arg.ServiceName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.Price,
			&i.UserUuid,
			&i.StartDate,
			&i.EndDate,
			&i.CancelationDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionById = `-- name: GetSubscriptionById :one
SELECT id, service_name, price, user_uuid, start_date, end_date, cancelation_date FROM subscriptions
WHERE id = $1
`

func (q *Queries) GetSubscriptionById(ctx context.Context, id sql.NullInt64) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionById, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserUuid,
		&i.StartDate,
		&i.EndDate,
		&i.CancelationDate,
	)
	return i, err
}
